version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    # For CPU-only (remove if you have GPU)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '4.0'
    #       memory: 8G

volumes:
  ollama_data: